### PR TITLE
Refactoring

### LINKED ISSUE #7: npm support & gulp plugin
Hey!

This issue builds on #6 slightly. I would like the ability to use this library on the server-side as well as on the client—I want to write a gulp plugin to run this library on HTML. Currently the way this library is structured, that is impossible.

It would be possible to restructure this library so that it works on both the client, but it would be a breaking change.

On the client:

```html
<script src="smartquotes.js></script>
<script> smartquotes() </script>
```

This approach would add the possibility to pass in options, such as saying they only want smart quotes and not em dashes, or restricting it to certain selectors.

On the server:

```js
var smartquotes = require('smartquotesjs');

var newHtml = smartquotes(oldHtml);
```

This could be done with as little inconvenience to your existing users as possible, while making it possible to use server-side, and create a gulp plugin.

If you'd be interested in this, I'd be willing to do it.

### PR DESCRIPTION
**Pull request by callumacrae**
- [x] UMD
- [x] ability to use on strings, for client-side
- [x] tests
- [x] docs

I've left the minified JS alone, not sure how you've done that. Would you like me to add a gulpfile so that it can handle the minification? It'll make it easier for collaborators.

closes #7

### CODE REVIEW

**Comment by callumacrae** [comment]
All done :smile: 

If you're happy with this, I think this is probably worth a 1.0.0 release. It definitely breaks backward compabilitity (technically okay pre-1.0.0, but could annoy people), and also adds tests, which is probably useful. I'd recommend getting travis working on this repo :smile:

**Comment by kemitchell** [comment]
`smartquotesjs` looks to be available on npm. I have [`smart-quotes`](https://www.npmjs.com/package/smart-quotes), which is just an earlier version of this repo. I'd be happy to hand over `smart-quotes` or deprecate it when this refactoring is published to npm.

**Comment by callumacrae** [comment]
Sure it's available on npm, but it doesn't work unless you're using it client-side. Or am I misunderstanding you?

**Comment by kellym** [comment]
I think that was in reference to the name being available?

**Comment by callumacrae** [comment]
Oh, right. Fair enough :)

**Comment by kemitchell** [comment]
@kellym it was. "smartquotesjs" is an available name on npm.

**Comment by kemitchell** [comment]
Although, to be fair, "smartquotes" would probably be better, and is also available.

**Comment by kellym** [comment]
agreed, I like "smartquotes" for npm -- looking through the PR now

**Comment by kellym** [comment]
*Love* splitting this into `string()` and `element()` -- I hated that it couldn't be used to parse just plain text. Nice changes!

I'm slightly averse to putting an `.editorconfig` file in the repo since it's more of a user-preferences type of thing, but I'm always flexible. 

If you want to add gulp to handle the minification, I'll +1 that.  I'd used a command line minifier in the past since the repo was so simple.

**Comment by callumacrae** [comment]
The editorconfig file is actually the opposite of that—the user can set their editor settings to whatever they want, but when they contribute to this project it means they use the existing code style, otherwise it gets messy. It means they don't have to change their editor settings.

I can remove if you want, though—that's why it's in its own commit!

**Comment by callumacrae** [comment]
I added an npm script to run uglifyjs, gulp would have been overkill :smile:

**Comment by callumacrae** [comment]
@kellym Hey! Any update on this?

**Comment by callumacrae** [comment]
@kellym: Sorry to nag, but I really want to use this library on my website and I can't until this PR is merged! Could you take a look at it?

If you're struggling for time, feel free to add me as a collaborator on this project and I'll keep it maintained for you :smiley:

**Comment by kellym** [comment]
LGTM. Sorry for the delays, busy last week and was out of town until last night. I'm going to get these issues cleaned up today and merge this one in. Also, I'm adding you as a collaborator -- great work on all of these changes, this is a perfect addition.

**Comment by callumacrae** [comment]
Awesome, thanks!

**Comment by kellym** [comment]
This has been published as v1.0.0 to npm at https://www.npmjs.com/package/smartquotes

**Comment by callumacrae** [comment]
:+1: I will start work on a gulp plugin :smiley_cat:

**Pull request merged**
