### PR TITLE
Convert dumb ellipses to smart ellipses (re #4)

### PR DESCRIPTION
**Pull request by jonahgreenthal**
Dashes will be my next attempt.

### CODE REVIEW

**Comment by kellym** [comment]
Sorry I've been hesitating on this one for so long.  I've been trying to figure out what to do in the case of someone putting four periods (or five or size) instead of three.  Should it just leave the extra period, or should it be smart enough to determine that someone is being excessive in their........ "typing"? :smiley_cat:

**Comment by callumacrae** [comment]
imo, `(?:.\s*){3,}`

**Comment by kellym** [comment]
So, after doing some digging into AP style and Chicago style (not that smartquotes really should care about those, but I don't want to break styles that are pretty commonly used), there are some things to think about:

- AP style: three periods with a space before and after.
- Chicago style: three periods with a space between each.

All the styles allow four periods in the case of the first one being the end of a sentence. 

In that case, we almost need to do a couple different filters:
```
.replace(/(\.)?\.{3,}/,"$1\u2026")
.replace(/(\.)?\s?(\.(\s|\Z)?){3,}/,"$1 . . .");
```
Which does these sorts of replacements:


end of sentence......   -> sentence.&hellip;
with spaces .... on the side -> spaces &hellip; on
somewhere in the... -> the&hellip;
Chicago ends this way. . . . . . . -> way. . . .
Chicago in the middle. . .should -> middle . . . should

**Comment by callumacrae** [comment]
What about stuff like this, though?

`something. . ... ..`

And why would you replace it with dots, instead of using an ellipsis?

**Comment by OliverM** [comment]
I think the Chicago & AP styles assume typography controls that aren't available on the web - you can't typeset arbitrary numbers of periods with the same visual rhythm as an ellipsis (in most fonts, though I guess you could do a custom glyph in a font, maybe?

For example, in the converted four-dot ellipsis above, there's a visible difference in spacing between the first dot and the ellipsis' dots. I think converting batches of three periods into an ellipsis is the best you can do, barring custom font implementations.

**Comment by kellym** [comment]
I'm going to go ahead and close this as smartquotes is meant to just deal with quotes. There are potentially other libraries out there to deal with ellipses. If not, it seems like it would be more feasible to build another library that has this one as a dependency to handle quotes, along with any other dependencies to handle other text formatting.

**Comment by kellym** [comment]
Just FYI I am thinking about another library to extend the features of this one.

**Pull request closed without merging**
